
// GENERATED by vt-go-graphql 2017-09-28 23:33:00.82423925 -0700 PDT
package vtgraphql_api

const SampleQueryTemporalDataObjectsRequest = `
{
	temporalDataObjects (applicationId: "STRING_VALUE", id: "STRING_VALUE", offset: 10234, limit: 10234)
  {records {createdDateTime modifiedDateTime id createdBy modifiedBy description name mediaId metadata {name }
jsondata 
	assets (id: "STRING_VALUE", assetType: "STRING_VALUE"){records {id name contentType description createdDateTime modifiedDateTime createdBy modifiedBy jsondata containerId uri assetType }
offset limit count }
security {global }
startDateTime stopDateTime source applicationId status tasks {records {id name description createdDateTime modifiedDateTime createdBy modifiedBy queuedDateTime completedDateTime status order isClone applicationId targetId engineId jobId buildId sourceAssetId mediaLengthSec taskPayload }
offset limit count }
}
offset limit count }

`

const SampleQueryTemporalDataObjectRequest = `
{
	temporalDataObject (id: "STRING_VALUE")
  {createdDateTime modifiedDateTime id createdBy modifiedBy description name mediaId metadata {name }
jsondata 
	assets (id: "STRING_VALUE", assetType: "STRING_VALUE"){records {id name contentType description createdDateTime modifiedDateTime createdBy modifiedBy jsondata containerId uri assetType }
offset limit count }
security {global }
startDateTime stopDateTime source applicationId status tasks {records {id name description createdDateTime modifiedDateTime createdBy modifiedBy queuedDateTime completedDateTime status order isClone applicationId targetId engineId jobId buildId sourceAssetId mediaLengthSec taskPayload }
offset limit count }
}

`

const SampleQueryAssetRequest = `
{
	asset (id: "STRING_VALUE")
  {id name contentType description createdDateTime modifiedDateTime createdBy modifiedBy jsondata containerId uri assetType }

`

const SampleQueryCloneRequestsRequest = `
{
	cloneRequests (id: "STRING_VALUE", applicationId: "STRING_VALUE", offset: 10234, limit: 10234)
  {records {id sourceApplicationId destinationApplicationId numberOfRecordings numberOfCompletedRecordings createdDateTime modifiedDateTime status percentage }
count offset limit }

`

const SampleQueryEnginesRequest = `
{
	engines (id: "STRING_VALUE", categoryId: "STRING_VALUE", state: [active,disabled,pending,deleted,draft,ready], owned: true or false, libraryRequired: true or false, offset: 10234, limit: 10234)
  {records {id ownerOrganizationId isPublic logoPath name description categoryId state price asset displayName validateUri executeUri applicationId createsRecording website rating createdDateTime modifiedDateTime createdBy modifiedBy deploymentModel 
	tasks (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy queuedDateTime completedDateTime status order isClone applicationId targetId engineId jobId buildId sourceAssetId mediaLengthSec taskPayload }
offset limit count }

	builds (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineId price validateUri executeUri status dockerImage runtime version report }
offset limit count }
}
count offset limit }

`

const SampleQueryEngineCategoriesRequest = `
{
	engineCategories (id: "STRING_VALUE")
  {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineIds totalEngines iconClass editable videoOnly }

`

const SampleQueryJobsRequest = `
{
	jobs (id: "STRING_VALUE", status: "STRING_VALUE", offset: 10234, limit: 10234, applicationId: "STRING_VALUE", targetId: "STRING_VALUE")
  {records {id name description createdDateTime modifiedDateTime createdBy modifiedBy targetId sourceAssetId 
	tasks (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE", targetId: "STRING_VALUE", applicationId: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy queuedDateTime completedDateTime status order isClone applicationId targetId engineId jobId buildId sourceAssetId mediaLengthSec taskPayload }
offset limit count }
applicationId }
offset limit count }

`

const SampleQueryEntityIdentifierTypesRequest = `
{
	entityIdentifierTypes (id: "STRING_VALUE", offset: 10234, limit: 10234)
  {records {id label labelPlural iconClass description dataType }
limit offset count }

`

const SampleQueryLibraryTypesRequest = `
{
	libraryTypes (id: "STRING_VALUE", offset: 10234, limit: 10234)
  {offset limit count records {id label iconClass entityIdentifierTypes {id label labelPlural iconClass description dataType }
entityTypeName entityTypeNamePlural entityType {name namePlural schema }
}
}

`

const SampleQueryLibrariesRequest = `
{
	libraries (id: "STRING_VALUE", name: "STRING_VALUE", offset: 10234, limit: 10234)
  {offset limit count records {createdDateTime modifiedDateTime id createdBy modifiedBy description name properties {name }
security {global }
version organizationId libraryType {id label iconClass entityIdentifierTypes {id label labelPlural iconClass description dataType }
entityTypeName entityTypeNamePlural entityType {name namePlural schema }
}
libraryTypeId coverImageUrl 
	engineModels (engineModelId: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy containerId libraryId library libraryVersion trainJobId trainStatus dataUrl jsondata }
offset limit count }

	entities (id: "STRING_VALUE", isPublished: true or false, identifierTypeId: "STRING_VALUE", name: "STRING_VALUE", offset: 10234, limit: 10234){offset limit count records {id name createdDateTime modifiedDateTime createdBy modifiedBy properties libraryId profileImageUrl 
	identifiers (id: "STRING_VALUE", identifierTypeId: "STRING_VALUE", offset: 10234, limit: 10234){records {id entityId identifierType identifierTypeId title isPriority createdDateTime modifiedDateTime url contentType jsondata }
offset limit count }
isPublished jsondata }
}

	collaborators (collaboratorOrgId: "STRING_VALUE"){records {organizationId organization {id name type applications {records {id key name category description iconUrl iconSvg url deploymentModel createdDateTime modifiedDateTime clientSecret oauth2RedirectUrls organizationId status permissionsRequired }
offset limit count }
jsondata createdDateTime modifiedDateTime seatLimit status roles {name permissions {records {id name description }
offset limit count }
id }
users {records {name id permissions roles organization jsondata }
offset limit count }
blacklist {organizationId engines {id ownerOrganizationId isPublic logoPath name description categoryId state price asset displayName validateUri executeUri applicationId createsRecording website rating createdDateTime modifiedDateTime createdBy modifiedBy deploymentModel 
	tasks (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy queuedDateTime completedDateTime status order isClone applicationId targetId engineId jobId buildId sourceAssetId mediaLengthSec taskPayload }
offset limit count }

	builds (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineId price validateUri executeUri status dockerImage runtime version report }
offset limit count }
}
engineCategories {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineIds totalEngines iconClass editable videoOnly }
}
whitelist {organizationId engines engineCategories }
schemas {records {schema name id ownerOrganizationId organization }
offset limit count }
watchlists {records {id name organization organizationId watchlistType marketName trackMyPrograms trackAll agencyId advertiserId brandId campaignId marketId budget mediaSourceTypeId startDate stopDate }
offset limit count }

	collections (name: "STRING_VALUE", offset: 10234, limit: 10234){records {id name imageUrl ownerId description organization organizationId orgSharing createdDateTime modifiedDateTime programCount itemCount typeId isActive 
	widgets (offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name organization organizationId collection collectionId displayCollectionName displayTranscription width numberOfMentionsToShow adScript seoTags backgroundColor borderColor textColor createdDateTime }
offset limit count }
}
offset limit count }

	rootFolder (type: [watchlist,collection,cms]){id name description createdDateTime modifiedDateTime ownerId parent subfolders organization organizationId maxDepth orderIndex status }
}
status createdDateTime modifiedDateTime permissions libraryId library }
offset limit count }
}
}

`

const SampleQueryLibraryRequest = `
{
	library (id: "STRING_VALUE")
  {createdDateTime modifiedDateTime id createdBy modifiedBy description name properties {name }
security {global }
version organizationId libraryType {id label iconClass entityIdentifierTypes {id label labelPlural iconClass description dataType }
entityTypeName entityTypeNamePlural entityType {name namePlural schema }
}
libraryTypeId coverImageUrl 
	engineModels (engineModelId: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy containerId libraryId library {createdDateTime modifiedDateTime id createdBy modifiedBy description name properties security version organizationId libraryType libraryTypeId coverImageUrl 
	engineModels (engineModelId: "STRING_VALUE")
	entities (id: "STRING_VALUE", isPublished: true or false, identifierTypeId: "STRING_VALUE", name: "STRING_VALUE", offset: 10234, limit: 10234){offset limit count records {id name createdDateTime modifiedDateTime createdBy modifiedBy properties libraryId profileImageUrl 
	identifiers (id: "STRING_VALUE", identifierTypeId: "STRING_VALUE", offset: 10234, limit: 10234){records {id entityId identifierType identifierTypeId title isPriority createdDateTime modifiedDateTime url contentType jsondata }
offset limit count }
isPublished jsondata }
}

	collaborators (collaboratorOrgId: "STRING_VALUE"){records {organizationId organization {id name type applications {records {id key name category description iconUrl iconSvg url deploymentModel createdDateTime modifiedDateTime clientSecret oauth2RedirectUrls organizationId status permissionsRequired }
offset limit count }
jsondata createdDateTime modifiedDateTime seatLimit status roles {name permissions {records {id name description }
offset limit count }
id }
users {records {name id permissions roles organization jsondata }
offset limit count }
blacklist {organizationId engines {id ownerOrganizationId isPublic logoPath name description categoryId state price asset displayName validateUri executeUri applicationId createsRecording website rating createdDateTime modifiedDateTime createdBy modifiedBy deploymentModel 
	tasks (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy queuedDateTime completedDateTime status order isClone applicationId targetId engineId jobId buildId sourceAssetId mediaLengthSec taskPayload }
offset limit count }

	builds (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineId price validateUri executeUri status dockerImage runtime version report }
offset limit count }
}
engineCategories {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineIds totalEngines iconClass editable videoOnly }
}
whitelist {organizationId engines engineCategories }
schemas {records {schema name id ownerOrganizationId organization }
offset limit count }
watchlists {records {id name organization organizationId watchlistType marketName trackMyPrograms trackAll agencyId advertiserId brandId campaignId marketId budget mediaSourceTypeId startDate stopDate }
offset limit count }

	collections (name: "STRING_VALUE", offset: 10234, limit: 10234){records {id name imageUrl ownerId description organization organizationId orgSharing createdDateTime modifiedDateTime programCount itemCount typeId isActive 
	widgets (offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name organization organizationId collection collectionId displayCollectionName displayTranscription width numberOfMentionsToShow adScript seoTags backgroundColor borderColor textColor createdDateTime }
offset limit count }
}
offset limit count }

	rootFolder (type: [watchlist,collection,cms]){id name description createdDateTime modifiedDateTime ownerId parent subfolders organization organizationId maxDepth orderIndex status }
}
status createdDateTime modifiedDateTime permissions libraryId library }
offset limit count }
}
libraryVersion trainJobId trainStatus dataUrl jsondata }
offset limit count }

	entities (id: "STRING_VALUE", isPublished: true or false, identifierTypeId: "STRING_VALUE", name: "STRING_VALUE", offset: 10234, limit: 10234)
	collaborators (collaboratorOrgId: "STRING_VALUE")}

`

const SampleQueryEntityRequest = `
{
	entity (id: "STRING_VALUE")
  {id name createdDateTime modifiedDateTime createdBy modifiedBy properties {name }
libraryId profileImageUrl 
	identifiers (id: "STRING_VALUE", identifierTypeId: "STRING_VALUE", offset: 10234, limit: 10234){records {id entityId identifierType {id label labelPlural iconClass description dataType }
identifierTypeId title isPriority createdDateTime modifiedDateTime url contentType jsondata }
offset limit count }
isPublished jsondata }

`

const SampleQueryApplicationsRequest = `
{
	applications (id: "STRING_VALUE", status: [active,draft,deleted,pending,rejected,approved,disabled], offset: 10234, limit: 10234)
  {records {id key name category description iconUrl iconSvg url deploymentModel createdDateTime modifiedDateTime clientSecret oauth2RedirectUrls organizationId status permissionsRequired }
offset limit count }

`

const SampleQueryOrganizationsRequest = `
{
	organizations (id: "STRING_VALUE", offset: 10234, limit: 10234)
  {records {id name type applications {records {id key name category description iconUrl iconSvg url deploymentModel createdDateTime modifiedDateTime clientSecret oauth2RedirectUrls organizationId status permissionsRequired }
offset limit count }
jsondata createdDateTime modifiedDateTime seatLimit status roles {name permissions {records {id name description }
offset limit count }
id }
users {records {name id permissions roles organization jsondata }
offset limit count }
blacklist {organizationId engines {id ownerOrganizationId isPublic logoPath name description categoryId state price asset displayName validateUri executeUri applicationId createsRecording website rating createdDateTime modifiedDateTime createdBy modifiedBy deploymentModel 
	tasks (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy queuedDateTime completedDateTime status order isClone applicationId targetId engineId jobId buildId sourceAssetId mediaLengthSec taskPayload }
offset limit count }

	builds (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineId price validateUri executeUri status dockerImage runtime version report }
offset limit count }
}
engineCategories {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineIds totalEngines iconClass editable videoOnly }
}
whitelist {organizationId engines engineCategories }
schemas {records {schema name id ownerOrganizationId organization }
offset limit count }
watchlists {records {id name organization organizationId watchlistType marketName trackMyPrograms trackAll agencyId advertiserId brandId campaignId marketId budget mediaSourceTypeId startDate stopDate }
offset limit count }

	collections (name: "STRING_VALUE", offset: 10234, limit: 10234){records {id name imageUrl ownerId description organization organizationId orgSharing createdDateTime modifiedDateTime programCount itemCount typeId isActive 
	widgets (offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name organization organizationId collection collectionId displayCollectionName displayTranscription width numberOfMentionsToShow adScript seoTags backgroundColor borderColor textColor createdDateTime }
offset limit count }
}
offset limit count }

	rootFolder (type: [watchlist,collection,cms]){id name description createdDateTime modifiedDateTime ownerId parent subfolders organization organizationId maxDepth orderIndex status }
}
offset limit count }

`

const SampleQueryOrganizationRequest = `
{
	organization (id: "STRING_VALUE")
  {id name type applications {records {id key name category description iconUrl iconSvg url deploymentModel createdDateTime modifiedDateTime clientSecret oauth2RedirectUrls organizationId status permissionsRequired }
offset limit count }
jsondata createdDateTime modifiedDateTime seatLimit status roles {name permissions {records {id name description }
offset limit count }
id }
users {records {name id permissions roles organization {id name type applications jsondata createdDateTime modifiedDateTime seatLimit status roles users blacklist {organizationId engines {id ownerOrganizationId isPublic logoPath name description categoryId state price asset displayName validateUri executeUri applicationId createsRecording website rating createdDateTime modifiedDateTime createdBy modifiedBy deploymentModel 
	tasks (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy queuedDateTime completedDateTime status order isClone applicationId targetId engineId jobId buildId sourceAssetId mediaLengthSec taskPayload }
offset limit count }

	builds (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineId price validateUri executeUri status dockerImage runtime version report }
offset limit count }
}
engineCategories {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineIds totalEngines iconClass editable videoOnly }
}
whitelist {organizationId engines engineCategories }
schemas {records {schema name id ownerOrganizationId organization }
offset limit count }
watchlists {records {id name organization organizationId watchlistType marketName trackMyPrograms trackAll agencyId advertiserId brandId campaignId marketId budget mediaSourceTypeId startDate stopDate }
offset limit count }

	collections (name: "STRING_VALUE", offset: 10234, limit: 10234){records {id name imageUrl ownerId description organization organizationId orgSharing createdDateTime modifiedDateTime programCount itemCount typeId isActive 
	widgets (offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name organization organizationId collection collectionId displayCollectionName displayTranscription width numberOfMentionsToShow adScript seoTags backgroundColor borderColor textColor createdDateTime }
offset limit count }
}
offset limit count }

	rootFolder (type: [watchlist,collection,cms]){id name description createdDateTime modifiedDateTime ownerId parent subfolders organization organizationId maxDepth orderIndex status }
}
jsondata }
offset limit count }
blacklist whitelist schemas watchlists 
	collections (name: "STRING_VALUE", offset: 10234, limit: 10234)
	rootFolder (type: [watchlist,collection,cms])}

`

const SampleQueryPermissionsRequest = `
{
	permissions (id: "STRING_VALUE", name: "STRING_VALUE", offset: 10234, limit: 10234)
  {records {id name description }
offset limit count }

`

const SampleQueryUsersRequest = `
{
	users (id: "STRING_VALUE", name: "STRING_VALUE", organizationIds: "STRING_VALUE", offset: 10234, limit: 10234)
  {records {name id permissions {records {id name description }
offset limit count }
roles {name permissions id }
organization {id name type applications {records {id key name category description iconUrl iconSvg url deploymentModel createdDateTime modifiedDateTime clientSecret oauth2RedirectUrls organizationId status permissionsRequired }
offset limit count }
jsondata createdDateTime modifiedDateTime seatLimit status roles users {records offset limit count }
blacklist {organizationId engines {id ownerOrganizationId isPublic logoPath name description categoryId state price asset displayName validateUri executeUri applicationId createsRecording website rating createdDateTime modifiedDateTime createdBy modifiedBy deploymentModel 
	tasks (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy queuedDateTime completedDateTime status order isClone applicationId targetId engineId jobId buildId sourceAssetId mediaLengthSec taskPayload }
offset limit count }

	builds (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineId price validateUri executeUri status dockerImage runtime version report }
offset limit count }
}
engineCategories {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineIds totalEngines iconClass editable videoOnly }
}
whitelist {organizationId engines engineCategories }
schemas {records {schema name id ownerOrganizationId organization }
offset limit count }
watchlists {records {id name organization organizationId watchlistType marketName trackMyPrograms trackAll agencyId advertiserId brandId campaignId marketId budget mediaSourceTypeId startDate stopDate }
offset limit count }

	collections (name: "STRING_VALUE", offset: 10234, limit: 10234){records {id name imageUrl ownerId description organization organizationId orgSharing createdDateTime modifiedDateTime programCount itemCount typeId isActive 
	widgets (offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name organization organizationId collection collectionId displayCollectionName displayTranscription width numberOfMentionsToShow adScript seoTags backgroundColor borderColor textColor createdDateTime }
offset limit count }
}
offset limit count }

	rootFolder (type: [watchlist,collection,cms]){id name description createdDateTime modifiedDateTime ownerId parent subfolders organization organizationId maxDepth orderIndex status }
}
jsondata }
offset limit count }

`

const SampleQueryUserRequest = `
{
	user (id: "STRING_VALUE")
  {name id permissions {records {id name description }
offset limit count }
roles {name permissions id }
organization {id name type applications {records {id key name category description iconUrl iconSvg url deploymentModel createdDateTime modifiedDateTime clientSecret oauth2RedirectUrls organizationId status permissionsRequired }
offset limit count }
jsondata createdDateTime modifiedDateTime seatLimit status roles users {records {name id permissions roles organization jsondata }
offset limit count }
blacklist {organizationId engines {id ownerOrganizationId isPublic logoPath name description categoryId state price asset displayName validateUri executeUri applicationId createsRecording website rating createdDateTime modifiedDateTime createdBy modifiedBy deploymentModel 
	tasks (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy queuedDateTime completedDateTime status order isClone applicationId targetId engineId jobId buildId sourceAssetId mediaLengthSec taskPayload }
offset limit count }

	builds (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineId price validateUri executeUri status dockerImage runtime version report }
offset limit count }
}
engineCategories {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineIds totalEngines iconClass editable videoOnly }
}
whitelist {organizationId engines engineCategories }
schemas {records {schema name id ownerOrganizationId organization }
offset limit count }
watchlists {records {id name organization organizationId watchlistType marketName trackMyPrograms trackAll agencyId advertiserId brandId campaignId marketId budget mediaSourceTypeId startDate stopDate }
offset limit count }

	collections (name: "STRING_VALUE", offset: 10234, limit: 10234){records {id name imageUrl ownerId description organization organizationId orgSharing createdDateTime modifiedDateTime programCount itemCount typeId isActive 
	widgets (offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name organization organizationId collection collectionId displayCollectionName displayTranscription width numberOfMentionsToShow adScript seoTags backgroundColor borderColor textColor createdDateTime }
offset limit count }
}
offset limit count }

	rootFolder (type: [watchlist,collection,cms]){id name description createdDateTime modifiedDateTime ownerId parent subfolders organization organizationId maxDepth orderIndex status }
}
jsondata }

`

const SampleQueryMeRequest = `
{
	me 
  {name id permissions {records {id name description }
offset limit count }
roles {name permissions id }
organization {id name type applications {records {id key name category description iconUrl iconSvg url deploymentModel createdDateTime modifiedDateTime clientSecret oauth2RedirectUrls organizationId status permissionsRequired }
offset limit count }
jsondata createdDateTime modifiedDateTime seatLimit status roles users {records {name id permissions roles organization jsondata }
offset limit count }
blacklist {organizationId engines {id ownerOrganizationId isPublic logoPath name description categoryId state price asset displayName validateUri executeUri applicationId createsRecording website rating createdDateTime modifiedDateTime createdBy modifiedBy deploymentModel 
	tasks (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy queuedDateTime completedDateTime status order isClone applicationId targetId engineId jobId buildId sourceAssetId mediaLengthSec taskPayload }
offset limit count }

	builds (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineId price validateUri executeUri status dockerImage runtime version report }
offset limit count }
}
engineCategories {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineIds totalEngines iconClass editable videoOnly }
}
whitelist {organizationId engines engineCategories }
schemas {records {schema name id ownerOrganizationId organization }
offset limit count }
watchlists {records {id name organization organizationId watchlistType marketName trackMyPrograms trackAll agencyId advertiserId brandId campaignId marketId budget mediaSourceTypeId startDate stopDate }
offset limit count }

	collections (name: "STRING_VALUE", offset: 10234, limit: 10234){records {id name imageUrl ownerId description organization organizationId orgSharing createdDateTime modifiedDateTime programCount itemCount typeId isActive 
	widgets (offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name organization organizationId collection collectionId displayCollectionName displayTranscription width numberOfMentionsToShow adScript seoTags backgroundColor borderColor textColor createdDateTime }
offset limit count }
}
offset limit count }

	rootFolder (type: [watchlist,collection,cms]){id name description createdDateTime modifiedDateTime ownerId parent subfolders organization organizationId maxDepth orderIndex status }
}
jsondata }

`

const SampleQueryGroupsRequest = `
{
	groups (id: "STRING_VALUE", name: "STRING_VALUE", organizationIds: "STRING_VALUE", offset: 10234, limit: 10234)
  {records {id createdDateTime modifiedDateTime applicationId createdBy {name id permissions {records {id name description }
offset limit count }
roles {name permissions id }
organization {id name type applications {records {id key name category description iconUrl iconSvg url deploymentModel createdDateTime modifiedDateTime clientSecret oauth2RedirectUrls organizationId status permissionsRequired }
offset limit count }
jsondata createdDateTime modifiedDateTime seatLimit status roles users {records offset limit count }
blacklist {organizationId engines {id ownerOrganizationId isPublic logoPath name description categoryId state price asset displayName validateUri executeUri applicationId createsRecording website rating createdDateTime modifiedDateTime createdBy modifiedBy deploymentModel 
	tasks (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy queuedDateTime completedDateTime status order isClone applicationId targetId engineId jobId buildId sourceAssetId mediaLengthSec taskPayload }
offset limit count }

	builds (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineId price validateUri executeUri status dockerImage runtime version report }
offset limit count }
}
engineCategories {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineIds totalEngines iconClass editable videoOnly }
}
whitelist {organizationId engines engineCategories }
schemas {records {schema name id ownerOrganizationId organization }
offset limit count }
watchlists {records {id name organization organizationId watchlistType marketName trackMyPrograms trackAll agencyId advertiserId brandId campaignId marketId budget mediaSourceTypeId startDate stopDate }
offset limit count }

	collections (name: "STRING_VALUE", offset: 10234, limit: 10234){records {id name imageUrl ownerId description organization organizationId orgSharing createdDateTime modifiedDateTime programCount itemCount typeId isActive 
	widgets (offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name organization organizationId collection collectionId displayCollectionName displayTranscription width numberOfMentionsToShow adScript seoTags backgroundColor borderColor textColor createdDateTime }
offset limit count }
}
offset limit count }

	rootFolder (type: [watchlist,collection,cms]){id name description createdDateTime modifiedDateTime ownerId parent subfolders organization organizationId maxDepth orderIndex status }
}
jsondata }
modifiedBy organizationId organization jsondata }
offset limit count }

`

const SampleQuerySearchMentionsRequest = `
{
	searchMentions (search: EH?)
  {jsondata }

`

const SampleQuerySearchMediaRequest = `
{
	searchMedia (search: EH?)
  {jsondata }

`

const SampleQueryFolderRequest = `
{
	folder (id: "STRING_VALUE")
  {id name description createdDateTime modifiedDateTime ownerId parent {id name description createdDateTime modifiedDateTime ownerId parent subfolders organization {id name type applications {records {id key name category description iconUrl iconSvg url deploymentModel createdDateTime modifiedDateTime clientSecret oauth2RedirectUrls organizationId status permissionsRequired }
offset limit count }
jsondata createdDateTime modifiedDateTime seatLimit status roles {name permissions {records {id name description }
offset limit count }
id }
users {records {name id permissions roles organization jsondata }
offset limit count }
blacklist {organizationId engines {id ownerOrganizationId isPublic logoPath name description categoryId state price asset displayName validateUri executeUri applicationId createsRecording website rating createdDateTime modifiedDateTime createdBy modifiedBy deploymentModel 
	tasks (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy queuedDateTime completedDateTime status order isClone applicationId targetId engineId jobId buildId sourceAssetId mediaLengthSec taskPayload }
offset limit count }

	builds (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineId price validateUri executeUri status dockerImage runtime version report }
offset limit count }
}
engineCategories {id name description createdDateTime modifiedDateTime createdBy modifiedBy engineIds totalEngines iconClass editable videoOnly }
}
whitelist {organizationId engines engineCategories }
schemas {records {schema name id ownerOrganizationId organization }
offset limit count }
watchlists {records {id name organization organizationId watchlistType marketName trackMyPrograms trackAll agencyId advertiserId brandId campaignId marketId budget mediaSourceTypeId startDate stopDate }
offset limit count }

	collections (name: "STRING_VALUE", offset: 10234, limit: 10234){records {id name imageUrl ownerId description organization organizationId orgSharing createdDateTime modifiedDateTime programCount itemCount typeId isActive 
	widgets (offset: 10234, limit: 10234, id: "STRING_VALUE"){records {id name organization organizationId collection collectionId displayCollectionName displayTranscription width numberOfMentionsToShow adScript seoTags backgroundColor borderColor textColor createdDateTime }
offset limit count }
}
offset limit count }

	rootFolder (type: [watchlist,collection,cms])}
organizationId maxDepth orderIndex status }
subfolders organization organizationId maxDepth orderIndex status }

`

const SampleQueryTaskRequest = `
{
	task (id: "STRING_VALUE")
  {id name description createdDateTime modifiedDateTime createdBy modifiedBy queuedDateTime completedDateTime status order isClone applicationId targetId engineId jobId buildId sourceAssetId mediaLengthSec taskPayload }

`

const SampleQueryJobRequest = `
{
	job (id: "STRING_VALUE")
  {id name description createdDateTime modifiedDateTime createdBy modifiedBy targetId sourceAssetId 
	tasks (status: "STRING_VALUE", offset: 10234, limit: 10234, id: "STRING_VALUE", targetId: "STRING_VALUE", applicationId: "STRING_VALUE"){records {id name description createdDateTime modifiedDateTime createdBy modifiedBy queuedDateTime completedDateTime status order isClone applicationId targetId engineId jobId buildId sourceAssetId mediaLengthSec taskPayload }
offset limit count }
applicationId }

`

const SampleQueryApplicationRequest = `
{
	application (id: "STRING_VALUE")
  {id key name category description iconUrl iconSvg url deploymentModel createdDateTime modifiedDateTime clientSecret oauth2RedirectUrls organizationId status permissionsRequired }

`

const SampleQueryIngestionConfigurationRequest = `
{
	ingestionConfiguration (id: "STRING_VALUE")
  {id applicationId type name createdDateTime modifiedDateTime emailAddress jsondata }

`

const SampleQueryIngestionConfigurationsRequest = `
{
	ingestionConfigurations (id: "STRING_VALUE", offset: 10234, limit: 10234, name: "STRING_VALUE", startDate: EH?, endDate: EH?, sources: "STRING_VALUE", applicationId: "STRING_VALUE", emailAddress: "STRING_VALUE")
  {offset limit count records {id applicationId type name createdDateTime modifiedDateTime emailAddress jsondata }
}

`

const SampleQueryGraphqlServiceInfoRequest = `
{
	graphqlServiceInfo 
  {buildInfo }

`

